### ISSUE TITLE
"process no longer exists" error message when running helix filter CWL

### ISSUE THREAD

**Issue by stevekm** [mskcc/helix_filters_01#1]
When running the helix filter CWL workflow, it consistently gives 1 or 2 of these error messages in the stdout log;

```
INFO [job maf_filter_33] /juno/work/ci/kellys5/projects/roslin-analysis-helper-dev/helix_filters_01/cache/e97dc9315c02054a5e8cdb59e0516529$ maf_filter.py \
    /tmp/tmpdlyei2fj/stg66f4c6b4-c98c-48ba-a2fd-e173cd4c1ca2/s_C_LELWCW_P001_d.s_C_LELWCW_N001_d.muts.maf.strip.txt \
    2.x \
    True \
    Project_1.muts.maf \
    data_mutations_extended.txt
Exception in thread Thread-83:
Traceback (most recent call last):
  File "/home/kellys5/projects/roslin-analysis-helper-dev/helix_filters_01/conda/lib/python3.6/site-packages/psutil/_common.py", line 449, in wrapper
    ret = self._cache[fun]
AttributeError: 'Process' object has no attribute '_cache'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/kellys5/projects/roslin-analysis-helper-dev/helix_filters_01/conda/lib/python3.6/site-packages/psutil/_pslinux.py", line 1516, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/kellys5/projects/roslin-analysis-helper-dev/helix_filters_01/conda/lib/python3.6/site-packages/psutil/_pslinux.py", line 1750, in memory_info
    with open_binary("%s/%s/statm" % (self._procfs_path, self.pid)) as f:
  File "/home/kellys5/projects/roslin-analysis-helper-dev/helix_filters_01/conda/lib/python3.6/site-packages/psutil/_common.py", line 713, in open_binary
    return open(fname, "rb", **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/proc/13515/statm'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/kellys5/projects/roslin-analysis-helper-dev/helix_filters_01/conda/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/kellys5/projects/roslin-analysis-helper-dev/helix_filters_01/conda/lib/python3.6/threading.py", line 1182, in run
    self.function(*self.args, **self.kwargs)
  File "/home/kellys5/projects/roslin-analysis-helper-dev/helix_filters_01/conda/lib/python3.6/site-packages/cwltool/job.py", line 483, in get_tree_mem_usage
    rss = monitor.memory_info().rss
  File "/home/kellys5/projects/roslin-analysis-helper-dev/helix_filters_01/conda/lib/python3.6/site-packages/psutil/_common.py", line 452, in wrapper
    return fun(self)
  File "/home/kellys5/projects/roslin-analysis-helper-dev/helix_filters_01/conda/lib/python3.6/site-packages/psutil/__init__.py", line 1070, in memory_info
    return self._proc.memory_info()
  File "/home/kellys5/projects/roslin-analysis-helper-dev/helix_filters_01/conda/lib/python3.6/site-packages/psutil/_pslinux.py", line 1523, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=13515)

```

Not sure what the significance of this is, it still completed the workflow successfully and the output files look alright.

**Comment by stevekm** [comment]
Have not seen this one in a while, maybe there was some HPC issue or something going on at the time
