### ISSUE TITLE
Concat cwl fails when handling listing

### ISSUE THREAD

**Issue by nikhil** [mskcc/helix_filters_01#4]
https://github.com/mskcc/helix_filters_01/blob/5488b2ac221311ef012f82d23a271d8a8034f175/cwl/concat.cwl#L17

The cwl fails on this line with ```TypeError: Cannot read property 'path' of undefined```

Input.json:
/juno/work/ci/temp/work/7fcd8a62-e9a7-4008-8f2e-2d9da7068d77/input.json

Full log:
/juno/work/ci/temp/work/7fcd8a62-e9a7-4008-8f2e-2d9da7068d77/lsf.log

Feel free to close if the inputs are not valid

**Comment by stevekm** [comment]
it looks like it has to do with only having a single .maf file in the input to the workflow.cwl since  I get the same error, running with cwltool

```
ERROR Exception on step 'concat_maf'
ERROR [step concat_maf] Cannot make job: Expression evaluation error:
Expecting value: line 1 column 1 (char 0)
script was:
01 "use strict";
02 var inputs = {
03     "input_files": [
04         {
05             "location": "file:///tmp/96rn70nz/Proj_08390_G.muts.maf",
06             "basename": "Proj_08390_G.muts.maf",
07             "nameroot": "Proj_08390_G.muts",
08             "nameext": ".maf",
09             "class": "File",
10             "checksum": "sha1$a054a8fbb14755b21da3c20964cb7f181de982bb",
11             "size": 16557,
12             "http://commonwl.org/cwltool#generation": 0,
13             "path": "/var/lib/cwl/stg46710bbc-f8fc-430e-90ac-ffa5d41e6a8d/Proj_08390_G.muts.maf",
14             "dirname": "/var/lib/cwl/stg46710bbc-f8fc-430e-90ac-ffa5d41e6a8d"
15         }
16     ]
17 };
18 var self = null;
19 var runtime = {
20     "cores": 1,
21     "ram": 1024,
22     "tmpdirSize": 1024,
23     "outdirSize": 1024,
24     "tmpdir": "/tmp",
25     "outdir": "/OcymKg"
26 };
27 (function(){return ((inputs.input_files[1].path));})()
stdout was: ''
stderr was: 'evalmachine.<anonymous>:27
(function(){return ((inputs.input_files[1].path));})()
                                          ^

TypeError: Cannot read property 'path' of undefined
    at evalmachine.<anonymous>:27:43
    at evalmachine.<anonymous>:27:53
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at Object.runInNewContext (vm.js:93:38)
    at Socket.<anonymous> ([eval]:11:57)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)'

INFO [workflow ] completed permanentFail
{
    "analysis_dir": null,
    "portal_dir": null
}
WARNING Final process status is permanentFail
make: *** [bash] Error 1
```

**Comment by stevekm** [comment]
So, the technical bug in this is fixed. However, it still seems like it is failing randomly in the workflow itself. Might be due to the workflow having some discrepancies in the inputs and outputs

**Comment by stevekm** [comment]
I think this is fixed so I will close this one
